# Build configuration for Home Assistant Add-on
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-advanced-options

build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.18

args:
  BUILD_FROM: ghcr.io/home-assistant/amd64-base:3.18
